<h1 id="pandas-errors-unsortedindexerror">pandas.errors.UnsortedIndexError</h1> <dl class="exception"> <dt id="pandas.errors.UnsortedIndexError">
<code>exception pandas.errors.UnsortedIndexError</code> <a class="reference external" href="http://github.com/pandas-dev/pandas/blob/v0.25.0/pandas/errors/__init__.py#L24-L30"><span class="viewcode-link">[source]</span></a>
</dt> <dd>
<p>Error raised when attempting to get a slice of a MultiIndex, and the index has not been lexsorted. Subclass of <code>KeyError</code>.</p> <div class="versionadded"> <p><span class="versionmodified">New in version 0.20.0.</span></p> </div> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2008&ndash;2012, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.errors.UnsortedIndexError.html" class="_attribution-link">https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.errors.UnsortedIndexError.html</a>
  </p>
</div>
