<h1>WP_Recovery_Mode::handle_error( array $error )</h1>  <section> <p>Handles a fatal error occurring.</p> </section> <div class="content-toc">  <section> <h2 id="description">Description</h2> <p>The calling API should immediately die() after calling this function.</p> </section>  <section> <h2 id="parameters">Parameters</h2> <dl> <dt>$error</dt> <dd> <p class="desc"> <span class="type">(<span class="array">array</span>)</span> <span class="required">(Required)</span> <span class="description">Error details from <code>error_get_last()</code>.</span> </p> </dd> </dl> </section>  <section> <h2 id="return">Return</h2> <p><span class="return-type">(true|<a href="../wp_error">WP_Error</a>)</span> True if the error was handled and headers have already been sent. Or the request will exit to try and catch multiple errors at once. <a href="../wp_error">WP_Error</a> if an error occurred preventing it from being handled.</p> </section>  <section> <h2 id="source">Source</h2> <p> File: <a href="https://developer.wordpress.org/reference/files/wp-includes/class-wp-recovery-mode.php/">wp-includes/class-wp-recovery-mode.php</a> </p> <pre data-language="php">public function handle_error( array $error ) {

		$extension = $this-&gt;get_extension_for_error( $error );

		if ( ! $extension || $this-&gt;is_network_plugin( $extension ) ) {
			return new WP_Error( 'invalid_source', __( 'Error not caused by a plugin or theme.' ) );
		}

		if ( ! $this-&gt;is_active() ) {
			if ( ! is_protected_endpoint() ) {
				return new WP_Error( 'non_protected_endpoint', __( 'Error occurred on a non-protected endpoint.' ) );
			}

			if ( ! function_exists( 'wp_generate_password' ) ) {
				require_once ABSPATH . WPINC . '/pluggable.php';
			}

			return $this-&gt;email_service-&gt;maybe_send_recovery_mode_email( $this-&gt;get_email_rate_limit(), $error, $extension );
		}

		if ( ! $this-&gt;store_error( $error ) ) {
			return new WP_Error( 'storage_error', __( 'Failed to store the error.' ) );
		}

		if ( headers_sent() ) {
			return true;
		}

		$this-&gt;redirect_protected();
	}</pre>  </section>  <section> <h2 id="related">Related</h2> <article class="uses"> <h3 id="uses">Uses</h3> <table id="uses-table">  <thead> <tr> <th>Uses</th> <th class="related-desc">Description</th> </tr> </thead> <tbody> <tr> <td> <span>wp-includes/class-wp-recovery-mode.php:</span> <a href="get_extension_for_error">WP_Recovery_Mode::get_extension_for_error()</a> </td> <td class="related-desc"> <p>Gets the extension that the error occurred in.</p> </td> </tr> <tr> <td> <span>wp-includes/class-wp-recovery-mode.php:</span> <a href="is_network_plugin">WP_Recovery_Mode::is_network_plugin()</a> </td> <td class="related-desc"> <p>Checks whether the given extension a network activated plugin.</p> </td> </tr> <tr> <td> <span>wp-includes/class-wp-recovery-mode.php:</span> <a href="store_error">WP_Recovery_Mode::store_error()</a> </td> <td class="related-desc"> <p>Stores the given error so that the extension causing it is paused.</p> </td> </tr> <tr> <td> <span>wp-includes/class-wp-recovery-mode.php:</span> <a href="redirect_protected">WP_Recovery_Mode::redirect_protected()</a> </td> <td class="related-desc"> <p>Redirects the current request to allow recovering multiple errors in one go.</p> </td> </tr> <tr> <td> <span>wp-includes/class-wp-recovery-mode.php:</span> <a href="is_active">WP_Recovery_Mode::is_active()</a> </td> <td class="related-desc"> <p>Checks whether recovery mode is active.</p> </td> </tr> <tr> <td> <span>wp-includes/class-wp-recovery-mode.php:</span> <a href="get_email_rate_limit">WP_Recovery_Mode::get_email_rate_limit()</a> </td> <td class="related-desc"> <p>Gets the rate limit between sending new recovery mode email links.</p> </td> </tr> <tr> <td> <span>wp-includes/load.php:</span> <a href="../../functions/is_protected_endpoint">is_protected_endpoint()</a> </td> <td class="related-desc"> <p>Determines whether we are currently on an endpoint that should be protected against WSODs.</p> </td> </tr> <tr> <td> <span>wp-includes/l10n.php:</span> <a href="../../functions/__">__()</a> </td> <td class="related-desc"> <p>Retrieve the translation of $text.</p> </td> </tr> <tr> <td> <span>wp-includes/class-wp-error.php:</span> <a href="../wp_error/__construct">WP_Error::__construct()</a> </td> <td class="related-desc"> <p>Initializes the error.</p> </td> </tr> </tbody>

</table>   </article>  <article class="used-by"> <h3 id="used-by">Used By</h3> <table id="used-by-table">  <thead> <tr> <th>Used By</th> <th class="related-desc">Description</th> </tr> </thead> <tbody> <tr> <td> <span>wp-includes/class-wp-fatal-error-handler.php:</span> <a href="../wp_fatal_error_handler/handle">WP_Fatal_Error_Handler::handle()</a> </td> <td class="related-desc"> <p>Runs the shutdown handler.</p> </td> </tr> </tbody>

</table> </article> </section>  <section> <h2 id="changelog">Changelog</h2> <table>  <thead> <tr> <th class="changelog-version">Version</th> <th class="changelog-desc">Description</th> </tr> </thead> <tbody> <tr> <td><a href="https://developer.wordpress.org/reference/since/5.2.0/" alt="WordPress 5.2.0">5.2.0</a></td> <td>Introduced.</td> </tr> </tbody> </table> </section>    </div><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://developer.wordpress.org/reference/classes/wp_recovery_mode/handle_error" class="_attribution-link" target="_blank">https://developer.wordpress.org/reference/classes/wp_recovery_mode/handle_error</a>
  </p>
</div>
