<h1>Class ExceptionInInitializerError</h1>   <ul class="inheritance"> <li><a href="object">java.lang.Object</a></li> <li> <ul class="inheritance"> <li><a href="throwable">java.lang.Throwable</a></li> <li> <ul class="inheritance"> <li><a href="error">java.lang.Error</a></li> <li> <ul class="inheritance"> <li><a href="linkageerror">java.lang.LinkageError</a></li> <li> <ul class="inheritance"> <li>java.lang.ExceptionInInitializerError</li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul>   <dl> <dt>All Implemented Interfaces:</dt> <dd><a href="../io/serializable">Serializable</a></dd> </dl>   <pre data-language="java">public class ExceptionInInitializerError
extends LinkageError</pre> <div>
<p>Signals that an unexpected exception has occurred in a static initializer. An <code>ExceptionInInitializerError</code> is thrown to indicate that an exception occurred during evaluation of a static initializer or the initializer for a static variable. </p>
<p>As of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The "saved throwable object" that may be provided at construction time and accessed via the <a href="exceptionininitializererror#getException--"><code>getException()</code></a> method is now known as the <i>cause</i>, and may be accessed via the <a href="throwable#getCause--"><code>Throwable.getCause()</code></a> method, as well as the aforementioned "legacy method."</p>
</div> <dl> <dt>Since:</dt> <dd>JDK1.1</dd>   </dl>       <h2 id="constructor.detail">Constructors</h2>   <h3 id="ExceptionInInitializerError--">ExceptionInInitializerError</h3> <pre data-language="java">public ExceptionInInitializerError()</pre> <p>Constructs an <code>ExceptionInInitializerError</code> with <code>null</code> as its detail message string and with no saved throwable object. A detail message is a String that describes this particular exception.</p>    <h3 id="ExceptionInInitializerError-java.lang.Throwable-">ExceptionInInitializerError</h3> <pre data-language="java">public ExceptionInInitializerError(Throwable thrown)</pre> <p>Constructs a new <code>ExceptionInInitializerError</code> class by saving a reference to the <code>Throwable</code> object thrown for later retrieval by the <a href="exceptionininitializererror#getException--"><code>getException()</code></a> method. The detail message string is set to <code>null</code>.</p> <dl> <dt>Parameters:</dt> <dd>
<code>thrown</code> - The exception thrown</dd> </dl>    <h3 id="ExceptionInInitializerError-java.lang.String-">ExceptionInInitializerError</h3> <pre data-language="java">public ExceptionInInitializerError(String s)</pre> <p>Constructs an ExceptionInInitializerError with the specified detail message string. A detail message is a String that describes this particular exception. The detail message string is saved for later retrieval by the <a href="throwable#getMessage--"><code>Throwable.getMessage()</code></a> method. There is no saved throwable object.</p> <dl> <dt>Parameters:</dt> <dd>
<code>s</code> - the detail message</dd> </dl>     <h2 id="method.detail">Methods</h2>   <h3 id="getException--">getException</h3> <pre data-language="java">public Throwable getException()</pre> <div>
<p>Returns the exception that occurred during a static initialization that caused this error to be created. </p>
<p>This method predates the general-purpose exception chaining facility. The <a href="throwable#getCause--"><code>Throwable.getCause()</code></a> method is now the preferred means of obtaining this information.</p>
</div> <dl> <dt>Returns:</dt> <dd>the saved throwable object of this <code>ExceptionInInitializerError</code>, or <code>null</code> if this <code>ExceptionInInitializerError</code> has no saved throwable object.</dd> </dl>    <h3 id="getCause--">getCause</h3> <pre data-language="java">public Throwable getCause()</pre> <p>Returns the cause of this error (the exception that occurred during a static initialization that caused this error to be created).</p> <dl> <dt>Overrides:</dt> <dd>
<code><a href="throwable#getCause--">getCause</a></code> in class <code><a href="throwable">Throwable</a></code>
</dd> <dt>Returns:</dt> <dd>the cause of this error or <code>null</code> if the cause is nonexistent or unknown.</dd> <dt>Since:</dt> <dd>1.4</dd> </dl>     <div class="_attribution">
  <p class="_attribution-p">
    &copy; 1993&ndash;2017, Oracle and/or its affiliates. All rights reserved.<br>Documentation extracted from Debian's OpenJDK Development Kit package.<br>Licensed under the GNU General Public License, version 2, with the Classpath Exception.<br>Various third party code in OpenJDK is licensed under different licenses (see Debian package).<br>Java and OpenJDK are trademarks or registered trademarks of Oracle and/or its affiliates.<br>
    
  </p>
</div>
