<h1>Class SaslException</h1>   <ul class="inheritance"> <li><a href="../../../java/lang/object">java.lang.Object</a></li> <li> <ul class="inheritance"> <li><a href="../../../java/lang/throwable">java.lang.Throwable</a></li> <li> <ul class="inheritance"> <li><a href="../../../java/lang/exception">java.lang.Exception</a></li> <li> <ul class="inheritance"> <li><a href="../../../java/io/ioexception">java.io.IOException</a></li> <li> <ul class="inheritance"> <li>javax.security.sasl.SaslException</li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul>   <dl> <dt>All Implemented Interfaces:</dt> <dd><a href="../../../java/io/serializable">Serializable</a></dd> </dl> <dl> <dt>Direct Known Subclasses:</dt> <dd><a href="authenticationexception">AuthenticationException</a></dd> </dl>   <pre data-language="java">public class SaslException
extends IOException</pre> <p>This class represents an error that has occurred when using SASL.</p> <dl> <dt>Since:</dt> <dd>1.5</dd>   </dl>       <h2 id="constructor.detail">Constructors</h2>   <h3 id="SaslException--">SaslException</h3> <pre data-language="java">public SaslException()</pre> <p>Constructs a new instance of <code>SaslException</code>. The root exception and the detailed message are null.</p>    <h3 id="SaslException-java.lang.String-">SaslException</h3> <pre data-language="java">public SaslException(String detail)</pre> <p>Constructs a new instance of <code>SaslException</code> with a detailed message. The root exception is null.</p> <dl> <dt>Parameters:</dt> <dd>
<code>detail</code> - A possibly null string containing details of the exception.</dd> <dt>See Also:</dt> <dd><a href="../../../java/lang/throwable#getMessage--"><code>Throwable.getMessage()</code></a></dd> </dl>    <h3 id="SaslException-java.lang.String-java.lang.Throwable-">SaslException</h3> <pre data-language="java">public SaslException(String detail,
                     Throwable ex)</pre> <p>Constructs a new instance of <code>SaslException</code> with a detailed message and a root exception. For example, a SaslException might result from a problem with the callback handler, which might throw a NoSuchCallbackException if it does not support the requested callback, or throw an IOException if it had problems obtaining data for the callback. The SaslException's root exception would be then be the exception thrown by the callback handler.</p> <dl> <dt>Parameters:</dt> <dd>
<code>detail</code> - A possibly null string containing details of the exception.</dd> <dd>
<code>ex</code> - A possibly null root exception that caused this exception.</dd> <dt>See Also:</dt> <dd>
<a href="../../../java/lang/throwable#getMessage--"><code>Throwable.getMessage()</code></a>, <a href="saslexception#getCause--"><code>getCause()</code></a>
</dd> </dl>     <h2 id="method.detail">Methods</h2>   <h3 id="getCause--">getCause</h3> <pre data-language="java">public Throwable getCause()</pre> <p>Description copied from class: <code><a href="../../../java/lang/throwable#getCause--">Throwable</a></code></p> <div>
<p>Returns the cause of this throwable or <code>null</code> if the cause is nonexistent or unknown. (The cause is the throwable that caused this throwable to get thrown.) </p>
<p>This implementation returns the cause that was supplied via one of the constructors requiring a <code>Throwable</code>, or that was set after creation with the <a href="../../../java/lang/throwable#initCause-java.lang.Throwable-"><code>Throwable.initCause(Throwable)</code></a> method. While it is typically unnecessary to override this method, a subclass can override it to return a cause set by some other means. This is appropriate for a "legacy chained throwable" that predates the addition of chained exceptions to <code>Throwable</code>. Note that it is <i>not</i> necessary to override any of the <code>PrintStackTrace</code> methods, all of which invoke the <code>getCause</code> method to determine the cause of a throwable.</p>
</div> <dl> <dt>Overrides:</dt> <dd>
<code><a href="../../../java/lang/throwable#getCause--">getCause</a></code> in class <code><a href="../../../java/lang/throwable">Throwable</a></code>
</dd> <dt>Returns:</dt> <dd>the cause of this throwable or <code>null</code> if the cause is nonexistent or unknown.</dd> </dl>    <h3 id="initCause-java.lang.Throwable-">initCause</h3> <pre data-language="java">public Throwable initCause(Throwable cause)</pre> <p>Description copied from class: <code><a href="../../../java/lang/throwable#initCause-java.lang.Throwable-">Throwable</a></code></p> <div>
<p>Initializes the <i>cause</i> of this throwable to the specified value. (The cause is the throwable that caused this throwable to get thrown.) </p>
<p>This method can be called at most once. It is generally called from within the constructor, or immediately after creating the throwable. If this throwable was created with <a href="../../../java/lang/throwable#Throwable-java.lang.Throwable-"><code>Throwable.Throwable(Throwable)</code></a> or <a href="../../../java/lang/throwable#Throwable-java.lang.String-java.lang.Throwable-"><code>Throwable.Throwable(String,Throwable)</code></a>, this method cannot be called even once. </p>
<p>An example of using this method on a legacy throwable type without other support for setting the cause is: </p>
<pre data-language="java">try {
     lowLevelOp();
 } catch (LowLevelException le) {
     throw (HighLevelException)
           new HighLevelException().initCause(le); // Legacy constructor
 }</pre>
</div> <dl> <dt>Overrides:</dt> <dd>
<code><a href="../../../java/lang/throwable#initCause-java.lang.Throwable-">initCause</a></code> in class <code><a href="../../../java/lang/throwable">Throwable</a></code>
</dd> <dt>Parameters:</dt> <dd>
<code>cause</code> - the cause (which is saved for later retrieval by the <a href="../../../java/lang/throwable#getCause--"><code>Throwable.getCause()</code></a> method). (A <code>null</code> value is permitted, and indicates that the cause is nonexistent or unknown.)</dd> <dt>Returns:</dt> <dd>a reference to this <code>Throwable</code> instance.</dd> </dl>    <h3 id="toString--">toString</h3> <pre data-language="java">public String toString()</pre> <p>Returns the string representation of this exception. The string representation contains this exception's class name, its detailed message, and if it has a root exception, the string representation of the root exception. This string representation is meant for debugging and not meant to be interpreted programmatically.</p> <dl> <dt>Overrides:</dt> <dd>
<code><a href="../../../java/lang/throwable#toString--">toString</a></code> in class <code><a href="../../../java/lang/throwable">Throwable</a></code>
</dd> <dt>Returns:</dt> <dd>The non-null string representation of this exception.</dd> <dt>See Also:</dt> <dd><a href="../../../java/lang/throwable#getMessage--"><code>Throwable.getMessage()</code></a></dd> </dl>     <div class="_attribution">
  <p class="_attribution-p">
    &copy; 1993&ndash;2017, Oracle and/or its affiliates. All rights reserved.<br>Documentation extracted from Debian's OpenJDK Development Kit package.<br>Licensed under the GNU General Public License, version 2, with the Classpath Exception.<br>Various third party code in OpenJDK is licensed under different licenses (see Debian package).<br>Java and OpenJDK are trademarks or registered trademarks of Oracle and/or its affiliates.<br>
    
  </p>
</div>
