<h1 class="fqn">Function std::array::try_from_fn</h1>
<pre class="rust fn" data-language="rust">pub fn try_from_fn&lt;E, F, T, const N:Â usize&gt;(cb: F) -&gt; Result&lt;[T; N], E&gt; whereÂ Â Â Â F: FnMut(usize) -&gt; Result&lt;T, E&gt;,Â </pre>
<div class="item-info"><div class="stab unstable">
<span class="emoji">ðŸ”¬</span> This is a nightly-only experimental API. (<code>array_from_fn</code> <a href="https://github.com/rust-lang/rust/issues/89379">#89379</a>)</div></div>
<p>Creates an array <code>[T; N]</code> where each fallible array element <code>T</code> is returned by the <code>cb</code> call. Unlike <code>core::array::from_fn</code>, where the element creation canâ€™t fail, this version will return an error if any element creation was unsuccessful.</p> <h3 id="arguments" class="section-header">Arguments</h3> <ul> <li>
<code>cb</code>: Callback where the passed argument is the current array index.</li> </ul> <h3 id="example" class="section-header">Example</h3> <div class="example-wrap"><pre class="rust rust-example-rendered" data-language="rust">#![feature(array_from_fn)]

#[derive(Debug, PartialEq)]
enum SomeError {
    Foo,
}

let array = core::array::try_from_fn(|i| Ok::&lt;_, SomeError&gt;(i));
assert_eq!(array, Ok([0, 1, 2, 3, 4]));

let another_array = core::array::try_from_fn::&lt;SomeError, _, (), 2&gt;(|_| Err(SomeError::Foo));
assert_eq!(another_array, Err(SomeError::Foo));</pre></div><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://doc.rust-lang.org/std/array/fn.try_from_fn.html" class="_attribution-link" target="_blank">https://doc.rust-lang.org/std/array/fn.try_from_fn.html</a>
  </p>
</div>
