<h1>Class NamingException</h1>   <ul class="inheritance"> <li><a href="../../java/lang/object">java.lang.Object</a></li> <li> <ul class="inheritance"> <li><a href="../../java/lang/throwable">java.lang.Throwable</a></li> <li> <ul class="inheritance"> <li><a href="../../java/lang/exception">java.lang.Exception</a></li> <li> <ul class="inheritance"> <li>javax.naming.NamingException</li> </ul> </li> </ul> </li> </ul> </li> </ul>   <dl> <dt>All Implemented Interfaces:</dt> <dd><a href="../../java/io/serializable">Serializable</a></dd> </dl> <dl> <dt>Direct Known Subclasses:</dt> <dd>
<a href="directory/attributeinuseexception">AttributeInUseException</a>, <a href="directory/attributemodificationexception">AttributeModificationException</a>, <a href="cannotproceedexception">CannotProceedException</a>, <a href="communicationexception">CommunicationException</a>, <a href="configurationexception">ConfigurationException</a>, <a href="contextnotemptyexception">ContextNotEmptyException</a>, <a href="insufficientresourcesexception">InsufficientResourcesException</a>, <a href="interruptednamingexception">InterruptedNamingException</a>, <a href="directory/invalidattributeidentifierexception">InvalidAttributeIdentifierException</a>, <a href="directory/invalidattributesexception">InvalidAttributesException</a>, <a href="directory/invalidattributevalueexception">InvalidAttributeValueException</a>, <a href="invalidnameexception">InvalidNameException</a>, <a href="directory/invalidsearchcontrolsexception">InvalidSearchControlsException</a>, <a href="directory/invalidsearchfilterexception">InvalidSearchFilterException</a>, <a href="limitexceededexception">LimitExceededException</a>, <a href="linkexception">LinkException</a>, <a href="namealreadyboundexception">NameAlreadyBoundException</a>, <a href="namenotfoundexception">NameNotFoundException</a>, <a href="namingsecurityexception">NamingSecurityException</a>, <a href="noinitialcontextexception">NoInitialContextException</a>, <a href="directory/nosuchattributeexception">NoSuchAttributeException</a>, <a href="notcontextexception">NotContextException</a>, <a href="operationnotsupportedexception">OperationNotSupportedException</a>, <a href="partialresultexception">PartialResultException</a>, <a href="referralexception">ReferralException</a>, <a href="directory/schemaviolationexception">SchemaViolationException</a>, <a href="serviceunavailableexception">ServiceUnavailableException</a>
</dd> </dl>   <pre data-language="java">public class NamingException
extends Exception</pre> <div>
<p>This is the superclass of all exceptions thrown by operations in the Context and DirContext interfaces. The nature of the failure is described by the name of the subclass. This exception captures the information pinpointing where the operation failed, such as where resolution last proceeded to. <ul> <li> Resolved Name. Portion of name that has been resolved. </li>
<li> Resolved Object. Object to which resolution of name proceeded. </li>
<li> Remaining Name. Portion of name that has not been resolved. </li>
<li> Explanation. Detail explaining why name resolution failed. </li>
<li> Root Exception. The exception that caused this naming exception to be thrown. </li>
</ul> null is an acceptable value for any of these fields. When null, it means that no such information has been recorded for that field. </p>
<p> A NamingException instance is not synchronized against concurrent multithreaded access. Multiple threads trying to access and modify a single NamingException instance should lock the object. </p>
<p> This exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The <i>root exception</i> (or <i>root cause</i>) is the same object as the <i>cause</i> returned by the <a href="../../java/lang/throwable#getCause--"><code>Throwable.getCause()</code></a> method.</p>
</div> <dl> <dt>Since:</dt> <dd>1.3</dd>   </dl>       <h2 id="field.detail">Fields</h2>   <h3 id="resolvedName">resolvedName</h3> <pre data-language="java">protected Name resolvedName</pre> <p>Contains the part of the name that has been successfully resolved. It is a composite name and can be null. This field is initialized by the constructors. You should access and manipulate this field through its get and set methods.</p> <dl> <dt>See Also:</dt> <dd>
<a href="namingexception#getResolvedName--"><code>getResolvedName()</code></a>, <a href="namingexception#setResolvedName-javax.naming.Name-"><code>setResolvedName(javax.naming.Name)</code></a>
</dd> </dl>    <h3 id="resolvedObj">resolvedObj</h3> <pre data-language="java">protected Object resolvedObj</pre> <p>Contains the object to which resolution of the part of the name was successful. Can be null. This field is initialized by the constructors. You should access and manipulate this field through its get and set methods.</p> <dl> <dt>See Also:</dt> <dd>
<a href="namingexception#getResolvedObj--"><code>getResolvedObj()</code></a>, <a href="namingexception#setResolvedObj-java.lang.Object-"><code>setResolvedObj(java.lang.Object)</code></a>
</dd> </dl>    <h3 id="remainingName">remainingName</h3> <pre data-language="java">protected Name remainingName</pre> <p>Contains the remaining name that has not been resolved yet. It is a composite name and can be null. This field is initialized by the constructors. You should access and manipulate this field through its get, set, "append" methods.</p> <dl> <dt>See Also:</dt> <dd>
<a href="namingexception#getRemainingName--"><code>getRemainingName()</code></a>, <a href="namingexception#setRemainingName-javax.naming.Name-"><code>setRemainingName(javax.naming.Name)</code></a>, <a href="namingexception#appendRemainingName-javax.naming.Name-"><code>appendRemainingName(javax.naming.Name)</code></a>, <a href="namingexception#appendRemainingComponent-java.lang.String-"><code>appendRemainingComponent(java.lang.String)</code></a>
</dd> </dl>    <h3 id="rootException">rootException</h3> <pre data-language="java">protected Throwable rootException</pre> <div>
<p>Contains the original exception that caused this NamingException to be thrown. This field is set if there is additional information that could be obtained from the original exception, or if the original exception could not be mapped to a subclass of NamingException. Can be null. </p>
<p> This field predates the general-purpose exception chaining facility. The <a href="namingexception#initCause-java.lang.Throwable-"><code>initCause(Throwable)</code></a> and <a href="namingexception#getCause--"><code>getCause()</code></a> methods are now the preferred means of accessing this information.</p>
</div> <dl> <dt>See Also:</dt> <dd>
<a href="namingexception#getRootCause--"><code>getRootCause()</code></a>, <a href="namingexception#setRootCause-java.lang.Throwable-"><code>setRootCause(Throwable)</code></a>, <a href="namingexception#initCause-java.lang.Throwable-"><code>initCause(Throwable)</code></a>, <a href="namingexception#getCause--"><code>getCause()</code></a>
</dd> </dl>     <h2 id="constructor.detail">Constructors</h2>   <h3 id="NamingException-java.lang.String-">NamingException</h3> <pre data-language="java">public NamingException(String explanation)</pre> <p>Constructs a new NamingException with an explanation. All unspecified fields are set to null.</p> <dl> <dt>Parameters:</dt> <dd>
<code>explanation</code> - A possibly null string containing additional detail about this exception.</dd> <dt>See Also:</dt> <dd><a href="../../java/lang/throwable#getMessage--"><code>Throwable.getMessage()</code></a></dd> </dl>    <h3 id="NamingException--">NamingException</h3> <pre data-language="java">public NamingException()</pre> <p>Constructs a new NamingException. All fields are set to null.</p>     <h2 id="method.detail">Methods</h2>   <h3 id="getResolvedName--">getResolvedName</h3> <pre data-language="java">public Name getResolvedName()</pre> <p>Retrieves the leading portion of the name that was resolved successfully.</p> <dl> <dt>Returns:</dt> <dd>The part of the name that was resolved successfully. It is a composite name. It can be null, which means the resolved name field has not been set.</dd> <dt>See Also:</dt> <dd>
<a href="namingexception#getResolvedObj--"><code>getResolvedObj()</code></a>, <a href="namingexception#setResolvedName-javax.naming.Name-"><code>setResolvedName(javax.naming.Name)</code></a>
</dd> </dl>    <h3 id="getRemainingName--">getRemainingName</h3> <pre data-language="java">public Name getRemainingName()</pre> <p>Retrieves the remaining unresolved portion of the name.</p> <dl> <dt>Returns:</dt> <dd>The part of the name that has not been resolved. It is a composite name. It can be null, which means the remaining name field has not been set.</dd> <dt>See Also:</dt> <dd>
<a href="namingexception#setRemainingName-javax.naming.Name-"><code>setRemainingName(javax.naming.Name)</code></a>, <a href="namingexception#appendRemainingName-javax.naming.Name-"><code>appendRemainingName(javax.naming.Name)</code></a>, <a href="namingexception#appendRemainingComponent-java.lang.String-"><code>appendRemainingComponent(java.lang.String)</code></a>
</dd> </dl>    <h3 id="getResolvedObj--">getResolvedObj</h3> <pre data-language="java">public Object getResolvedObj()</pre> <p>Retrieves the object to which resolution was successful. This is the object to which the resolved name is bound.</p> <dl> <dt>Returns:</dt> <dd>The possibly null object that was resolved so far. null means that the resolved object field has not been set.</dd> <dt>See Also:</dt> <dd>
<a href="namingexception#getResolvedName--"><code>getResolvedName()</code></a>, <a href="namingexception#setResolvedObj-java.lang.Object-"><code>setResolvedObj(java.lang.Object)</code></a>
</dd> </dl>    <h3 id="getExplanation--">getExplanation</h3> <pre data-language="java">public String getExplanation()</pre> <p>Retrieves the explanation associated with this exception.</p> <dl> <dt>Returns:</dt> <dd>The possibly null detail string explaining more about this exception. If null, it means there is no detail message for this exception.</dd> <dt>See Also:</dt> <dd><a href="../../java/lang/throwable#getMessage--"><code>Throwable.getMessage()</code></a></dd> </dl>    <h3 id="setResolvedName-javax.naming.Name-">setResolvedName</h3> <pre data-language="java">public void setResolvedName(Name name)</pre> <div>
<p>Sets the resolved name field of this exception. </p>
<p> <code>name</code> is a composite name. If the intent is to set this field using a compound name or string, you must "stringify" the compound name, and create a composite name with a single component using the string. You can then invoke this method using the resulting composite name. </p>
<p> A copy of <code>name</code> is made and stored. Subsequent changes to <code>name</code> does not affect the copy in this NamingException and vice versa.</p>
</div> <dl> <dt>Parameters:</dt> <dd>
<code>name</code> - The possibly null name to set resolved name to. If null, it sets the resolved name field to null.</dd> <dt>See Also:</dt> <dd><a href="namingexception#getResolvedName--"><code>getResolvedName()</code></a></dd> </dl>    <h3 id="setRemainingName-javax.naming.Name-">setRemainingName</h3> <pre data-language="java">public void setRemainingName(Name name)</pre> <div>
<p>Sets the remaining name field of this exception. </p>
<p> <code>name</code> is a composite name. If the intent is to set this field using a compound name or string, you must "stringify" the compound name, and create a composite name with a single component using the string. You can then invoke this method using the resulting composite name. </p>
<p> A copy of <code>name</code> is made and stored. Subsequent changes to <code>name</code> does not affect the copy in this NamingException and vice versa.</p>
</div> <dl> <dt>Parameters:</dt> <dd>
<code>name</code> - The possibly null name to set remaining name to. If null, it sets the remaining name field to null.</dd> <dt>See Also:</dt> <dd>
<a href="namingexception#getRemainingName--"><code>getRemainingName()</code></a>, <a href="namingexception#appendRemainingName-javax.naming.Name-"><code>appendRemainingName(javax.naming.Name)</code></a>, <a href="namingexception#appendRemainingComponent-java.lang.String-"><code>appendRemainingComponent(java.lang.String)</code></a>
</dd> </dl>    <h3 id="setResolvedObj-java.lang.Object-">setResolvedObj</h3> <pre data-language="java">public void setResolvedObj(Object obj)</pre> <p>Sets the resolved object field of this exception.</p> <dl> <dt>Parameters:</dt> <dd>
<code>obj</code> - The possibly null object to set resolved object to. If null, the resolved object field is set to null.</dd> <dt>See Also:</dt> <dd><a href="namingexception#getResolvedObj--"><code>getResolvedObj()</code></a></dd> </dl>    <h3 id="appendRemainingComponent-java.lang.String-">appendRemainingComponent</h3> <pre data-language="java">public void appendRemainingComponent(String name)</pre> <p>Add name as the last component in remaining name.</p> <dl> <dt>Parameters:</dt> <dd>
<code>name</code> - The component to add. If name is null, this method does not do anything.</dd> <dt>See Also:</dt> <dd>
<a href="namingexception#setRemainingName-javax.naming.Name-"><code>setRemainingName(javax.naming.Name)</code></a>, <a href="namingexception#getRemainingName--"><code>getRemainingName()</code></a>, <a href="namingexception#appendRemainingName-javax.naming.Name-"><code>appendRemainingName(javax.naming.Name)</code></a>
</dd> </dl>    <h3 id="appendRemainingName-javax.naming.Name-">appendRemainingName</h3> <pre data-language="java">public void appendRemainingName(Name name)</pre> <div>
<p>Add components from 'name' as the last components in remaining name. </p>
<p> <code>name</code> is a composite name. If the intent is to append a compound name, you should "stringify" the compound name then invoke the overloaded form that accepts a String parameter. </p>
<p> Subsequent changes to <code>name</code> does not affect the remaining name field in this NamingException and vice versa.</p>
</div> <dl> <dt>Parameters:</dt> <dd>
<code>name</code> - The possibly null name containing ordered components to add. If name is null, this method does not do anything.</dd> <dt>See Also:</dt> <dd>
<a href="namingexception#setRemainingName-javax.naming.Name-"><code>setRemainingName(javax.naming.Name)</code></a>, <a href="namingexception#getRemainingName--"><code>getRemainingName()</code></a>, <a href="namingexception#appendRemainingComponent-java.lang.String-"><code>appendRemainingComponent(java.lang.String)</code></a>
</dd> </dl>    <h3 id="getRootCause--">getRootCause</h3> <pre data-language="java">public Throwable getRootCause()</pre> <div>
<p>Retrieves the root cause of this NamingException, if any. The root cause of a naming exception is used when the service provider wants to indicate to the caller a non-naming related exception but at the same time wants to use the NamingException structure to indicate how far the naming operation proceeded. </p>
<p> This method predates the general-purpose exception chaining facility. The <a href="namingexception#getCause--"><code>getCause()</code></a> method is now the preferred means of obtaining this information.</p>
</div> <dl> <dt>Returns:</dt> <dd>The possibly null exception that caused this naming exception. If null, it means no root cause has been set for this naming exception.</dd> <dt>See Also:</dt> <dd>
<a href="namingexception#setRootCause-java.lang.Throwable-"><code>setRootCause(java.lang.Throwable)</code></a>, <a href="namingexception#rootException"><code>rootException</code></a>, <a href="namingexception#getCause--"><code>getCause()</code></a>
</dd> </dl>    <h3 id="setRootCause-java.lang.Throwable-">setRootCause</h3> <pre data-language="java">public void setRootCause(Throwable e)</pre> <div>
<p>Records the root cause of this NamingException. If <code>e</code> is <code>this</code>, this method does not do anything. </p>
<p> This method predates the general-purpose exception chaining facility. The <a href="namingexception#initCause-java.lang.Throwable-"><code>initCause(Throwable)</code></a> method is now the preferred means of recording this information.</p>
</div> <dl> <dt>Parameters:</dt> <dd>
<code>e</code> - The possibly null exception that caused the naming operation to fail. If null, it means this naming exception has no root cause.</dd> <dt>See Also:</dt> <dd>
<a href="namingexception#getRootCause--"><code>getRootCause()</code></a>, <a href="namingexception#rootException"><code>rootException</code></a>, <a href="namingexception#initCause-java.lang.Throwable-"><code>initCause(java.lang.Throwable)</code></a>
</dd> </dl>    <h3 id="getCause--">getCause</h3> <pre data-language="java">public Throwable getCause()</pre> <p>Returns the cause of this exception. The cause is the throwable that caused this naming exception to be thrown. Returns <code>null</code> if the cause is nonexistent or unknown.</p> <dl> <dt>Overrides:</dt> <dd>
<code><a href="../../java/lang/throwable#getCause--">getCause</a></code> in class <code><a href="../../java/lang/throwable">Throwable</a></code>
</dd> <dt>Returns:</dt> <dd>the cause of this exception, or <code>null</code> if the cause is nonexistent or unknown.</dd> <dt>Since:</dt> <dd>1.4</dd> <dt>See Also:</dt> <dd><a href="namingexception#initCause-java.lang.Throwable-"><code>initCause(Throwable)</code></a></dd> </dl>    <h3 id="initCause-java.lang.Throwable-">initCause</h3> <pre data-language="java">public Throwable initCause(Throwable cause)</pre> <div>
<p>Initializes the cause of this exception to the specified value. The cause is the throwable that caused this naming exception to be thrown. </p>
<p> This method may be called at most once.</p>
</div> <dl> <dt>Overrides:</dt> <dd>
<code><a href="../../java/lang/throwable#initCause-java.lang.Throwable-">initCause</a></code> in class <code><a href="../../java/lang/throwable">Throwable</a></code>
</dd> <dt>Parameters:</dt> <dd>
<code>cause</code> - the cause, which is saved for later retrieval by the <a href="namingexception#getCause--"><code>getCause()</code></a> method. A <code>null</code> value indicates that the cause is nonexistent or unknown.</dd> <dt>Returns:</dt> <dd>a reference to this <code>NamingException</code> instance.</dd> <dt>Throws:</dt> <dd>
<code><a href="../../java/lang/illegalargumentexception">IllegalArgumentException</a></code> - if <code>cause</code> is this exception. (A throwable cannot be its own cause.)</dd> <dd>
<code><a href="../../java/lang/illegalstateexception">IllegalStateException</a></code> - if this method has already been called on this exception.</dd> <dt>Since:</dt> <dd>1.4</dd> <dt>See Also:</dt> <dd><a href="namingexception#getCause--"><code>getCause()</code></a></dd> </dl>    <h3 id="toString--">toString</h3> <pre data-language="java">public String toString()</pre> <p>Generates the string representation of this exception. The string representation consists of this exception's class name, its detailed message, and if it has a root cause, the string representation of the root cause exception, followed by the remaining name (if it is not null). This string is used for debugging and not meant to be interpreted programmatically.</p> <dl> <dt>Overrides:</dt> <dd>
<code><a href="../../java/lang/throwable#toString--">toString</a></code> in class <code><a href="../../java/lang/throwable">Throwable</a></code>
</dd> <dt>Returns:</dt> <dd>The non-null string containing the string representation of this exception.</dd> </dl>    <h3 id="toString-boolean-">toString</h3> <pre data-language="java">public String toString(boolean detail)</pre> <p>Generates the string representation in more detail. This string representation consists of the information returned by the toString() that takes no parameters, plus the string representation of the resolved object (if it is not null). This string is used for debugging and not meant to be interpreted programmatically.</p> <dl> <dt>Parameters:</dt> <dd>
<code>detail</code> - If true, include details about the resolved object in addition to the other information.</dd> <dt>Returns:</dt> <dd>The non-null string containing the string representation.</dd> </dl>     <div class="_attribution">
  <p class="_attribution-p">
    &copy; 1993&ndash;2017, Oracle and/or its affiliates. All rights reserved.<br>Documentation extracted from Debian's OpenJDK Development Kit package.<br>Licensed under the GNU General Public License, version 2, with the Classpath Exception.<br>Various third party code in OpenJDK is licensed under different licenses (see Debian package).<br>Java and OpenJDK are trademarks or registered trademarks of Oracle and/or its affiliates.<br>
    
  </p>
</div>
