<div class="innertube"> <h1 id="Errors and Error Handling">12 Errors and Error Handling</h1> <h2 id="terminology" class="title-link" onmouseover="document.getElementById('ghlink-terminology-idm3071').style.visibility = 'visible';" onmouseout="document.getElementById('ghlink-terminology-idm3071').style.visibility = 'hidden';"> <div class="title-name">12.1 Terminology</div>  </h2> <p>Errors can roughly be divided into four different types:</p> <dl> <dt><strong>Compile-time errors</strong></dt> <dd>When the compiler fails to compile the program, for example a syntax error.</dd> <dt><strong>Logical errors</strong></dt> <dd>When a program does not behave as intended, but does not crash. An example is that nothing happens when a button in a graphical user interface is clicked.</dd> <dt><strong id="run-time-errors">Run-time errors</strong></dt> <dd>When a crash occurs. An example is when an operator is applied to arguments of the wrong type. The Erlang programming language has built-in features for handling of run-time errors. A run-time error can also be emulated by calling <code> <span class="code">error(Reason)</span></code>. Run-time errors are exceptions of class <code class="code">error</code>.</dd> <dt><strong id="generated-errors">Generated errors</strong></dt> <dd>When the code itself calls <code> <span class="code">exit/1</span></code> or <code> <span class="code">throw/1</span></code>. Generated errors are exceptions of class <code class="code">exit</code> or <code class="code">throw</code>.</dd> </dl> <p>When an exception occurs in Erlang, execution of the process that evaluated the erroneous expression is stopped. This is referred to as a <strong>failure</strong>, that execution or evaluation <strong>fails</strong>, or that the process <strong>fails</strong>, <strong>terminates</strong>, or <strong>exits</strong>. Notice that a process can terminate/exit for other reasons than a failure.</p> <p>A process that terminates emits an <strong>exit signal</strong> with an <strong>exit reason</strong> that describes why the process terminated. Normally, some information about any erroneous termination is printed to the terminal. See <code><a href="processes#term"> Process Termination</a></code> in the Processes chapter for more details on termination.</p> <h2 id="exceptions" class="title-link" onmouseover="document.getElementById('ghlink-exceptions-idm3104').style.visibility = 'visible';" onmouseout="document.getElementById('ghlink-exceptions-idm3104').style.visibility = 'hidden';"> <div class="title-name">12.2 Exceptions</div>  </h2> <p>Exceptions are <code><a href="#run-time-errors">run-time errors</a></code> or <code><a href="#generated-errors">generated errors</a></code> and are of three different classes, with different origins. The <code><a href="expressions#try">try</a></code> expression can distinguish between the different classes, whereas the <code><a href="expressions#catch">catch</a></code> expression cannot. <code class="code">try</code> and <code class="code">catch</code> are described in <code><a href="expressions">Expressions</a></code>.</p> <div class="doc-table-wrapper"> <table class="doc-table"> <tr> <td><strong>Class</strong></td> <td><strong>Origin</strong></td> </tr> <tr> <td><code class="code">error</code></td> <td>Run-time error, for example, <code class="code">1+a</code>, or the process called <code class="code">error/1,2</code> </td> </tr> <tr> <td><code class="code">exit</code></td> <td>The process called <code class="code">exit/1</code> </td> </tr> <tr> <td><code class="code">throw</code></td> <td>The process called <code class="code">throw/1</code> </td> </tr> </table> <p class="doc-table-caption">Table 12.1: Exception Classes.</p> </div> <p>All of the above exceptions can also be generated by calling <code><span class="code">erlang:raise/3</span></code>.</p> <p>An exception consists of its class, an exit reason (see <code><a href="#exit_reasons">Exit Reason</a></code>), and a stack trace (which aids in finding the code location of the exception).</p> <p>The stack trace can be bound to a variable from within a <code class="code">try</code> expression for any exception class, or as part of the exit reason when a run-time error is caught by a <code class="code">catch</code>. Example:</p> <pre data-language="erlang">
&gt; {'EXIT',{test,Stacktrace}} = (catch error(test)), Stacktrace.
[{shell,apply_fun,3,[]},
 {erl_eval,do_apply,6,[]},
 ...]
&gt; try throw(test) catch Class:Reason:Stacktrace -&gt; Stacktrace end.
[{shell,apply_fun,3,[]},
 {erl_eval,do_apply,6,[]},
 ...]</pre> <h4 id="the-call-stack-back-trace--stacktrace-" class="title-link" onmouseover="document.getElementById('ghlink-the-call-stack-back-trace--stacktrace--idm3148').style.visibility = 'visible';" onmouseout="document.getElementById('ghlink-the-call-stack-back-trace--stacktrace--idm3148').style.visibility = 'hidden';"> <div class="title-name">The call-stack back trace (stacktrace)</div>  </h4> <p>The stack back-trace (<code><strong>stacktrace</strong></code>) is a list contains <code class="code">{Module, Function, Arity, ExtraInfo}</code> and/or <code class="code">{Fun, Arity, ExtraInfo}</code> tuples. The field <code class="code">Arity</code> in the tuple can be the argument list of that function call instead of an arity integer, depending on the exception.</p> <p><code class="code">ExtraInfo</code> is a (possibly empty) list of two-element tuples in any order that provides additional information about the exception. The first element is an atom describing the type of information in the second element. The following items can occur:</p> <dl> <dt><strong><code class="code">error_info</code></strong></dt> <dd>The second element of the tuple is a map providing additional information about what caused the exception. This information can be created by calling <code><span class="code">error/3</span></code> and is used by <code> <span class="code">erl_error:format_exception/4</span></code>. </dd> <dt><strong><code class="code">file</code></strong></dt> <dd>The second element of the tuple is a string (list of characters) representing the filename of the source file of the function. </dd> <dt><strong><code class="code">line</code></strong></dt> <dd>The second element of the tuple is the line number (an integer &gt; 0) in the source file where the exception occurred or the function was called. </dd> </dl> <div class="warning"> <div class="label">Warning</div> <div class="content">

<p>Developers should rely on stacktrace entries only for debugging purposes.</p> <p>The VM performs tail call optimization, which does not add new entries to the stacktrace, and also limits stacktraces to a certain depth. Furthermore, compiler options, optimizations and future changes may add or remove stacktrace entries, causing any code that expects the stacktrace to be in a certain order or contain specific items to fail.</p> <p>The only exception to this rule is the class <code class="code">error</code> with the reason <code class="code">undef</code> which is guaranteed to include the <code class="code">Module</code>, <code class="code">Function</code> and <code class="code">Arity</code> of the attempted function as the first stacktrace entry.</p> </div> </div> <h2 id="handling-of-run-time-errors-in-erlang" class="title-link" onmouseover="document.getElementById('ghlink-handling-of-run-time-errors-in-erlang-idm3182').style.visibility = 'visible';" onmouseout="document.getElementById('ghlink-handling-of-run-time-errors-in-erlang-idm3182').style.visibility = 'hidden';"> <div class="title-name">12.3 Handling of Run-time Errors in Erlang</div>  </h2> <h4 id="error-handling-within-processes" class="title-link" onmouseover="document.getElementById('ghlink-error-handling-within-processes-idm3184').style.visibility = 'visible';" onmouseout="document.getElementById('ghlink-error-handling-within-processes-idm3184').style.visibility = 'hidden';"> <div class="title-name">Error Handling Within Processes</div>  </h4> <p>It is possible to prevent run-time errors and other exceptions from causing the process to terminate by using <code class="code">catch</code> or <code class="code">try</code>, see <code><a href="expressions"> Expressions</a></code> about <code><a href="expressions#catch">catch</a></code> and <code><a href="expressions#try">try</a></code>.</p> <h4 id="error-handling-between-processes" class="title-link" onmouseover="document.getElementById('ghlink-error-handling-between-processes-idm3192').style.visibility = 'visible';" onmouseout="document.getElementById('ghlink-error-handling-between-processes-idm3192').style.visibility = 'hidden';"> <div class="title-name">Error Handling Between Processes</div>  </h4> <p>Processes can monitor other processes and detect process terminations, see <code><a href="processes#errors">Processes</a></code>.</p> <h2 id="exit-reasons" class="title-link" onmouseover="document.getElementById('ghlink-exit-reasons-idm3196').style.visibility = 'visible';" onmouseout="document.getElementById('ghlink-exit-reasons-idm3196').style.visibility = 'hidden';"> <div class="title-name">12.4 Exit Reasons</div>  </h2> <p>When a run-time error occurs, that is an exception of class <code class="code">error</code>. The exit reason is a tuple <code class="code">{Reason,Stack}</code>, where <code class="code">Reason</code> is a term indicating the type of error:</p> <div class="doc-table-wrapper"> <table class="doc-table"> <tr> <td><strong>Reason</strong></td> <td><strong>Type of Error</strong></td> </tr> <tr> <td><code class="code">badarg</code></td> <td>Bad argument. The argument is of wrong data type, or is otherwise badly formed.</td> </tr> <tr> <td><code class="code">badarith</code></td> <td>Bad argument in an arithmetic expression.</td> </tr> <tr> <td><code class="code">{badmatch,V}</code></td> <td>Evaluation of a match expression failed. The value <code class="code">V</code> did not match.</td> </tr> <tr> <td><code class="code">function_clause</code></td> <td>No matching function clause is found when evaluating a function call.</td> </tr> <tr> <td><code class="code">{case_clause,V}</code></td> <td>No matching branch is found when evaluating a <code class="code">case</code> expression. The value <code class="code">V</code> did not match.</td> </tr> <tr> <td><code class="code">if_clause</code></td> <td>No true branch is found when evaluating an <code class="code">if</code> expression.</td> </tr> <tr> <td><code class="code">{try_clause,V}</code></td> <td>No matching branch is found when evaluating the of-section of a <code class="code">try</code> expression. The value <code class="code">V</code> did not match.</td> </tr> <tr> <td><code class="code">undef</code></td> <td>The function cannot be found when evaluating a function call.</td> </tr> <tr> <td><code class="code">{badfun,F}</code></td> <td>Something is wrong with a fun <code class="code">F</code>.</td> </tr> <tr> <td><code class="code">{badarity,F}</code></td> <td>A fun is applied to the wrong number of arguments. <code class="code">F</code> describes the fun and the arguments.</td> </tr> <tr> <td><code class="code">timeout_value</code></td> <td>The timeout value in a <code class="code">receive..after</code> expression is evaluated to something else than an integer or <code class="code">infinity</code>.</td> </tr> <tr> <td><code class="code">noproc</code></td> <td>Trying to link or monitor to a non-existing process or port.</td> </tr> <tr> <td><code class="code">noconnection</code></td> <td>A link or monitor to a remote process was broken because a connection between the nodes could not be established or was severed.</td> </tr> <tr> <td><code class="code">{nocatch,V}</code></td> <td>Trying to evaluate a <code class="code">throw</code>outside a <code class="code">catch</code>. <code class="code">V</code> is the thrown term.</td> </tr> <tr> <td><code class="code">system_limit</code></td> <td>A system limit has been reached. See <code> Efficiency Guide</code> for information about system limits. </td> </tr> </table> <p class="doc-table-caption">Table 12.2: Exit Reasons</p> </div> <p><code class="code">Stack</code> is the stack of function calls being evaluated when the error occurred, given as a list of tuples <code class="code">{Module,Name,Arity,ExtraInfo}</code> with the most recent function call first. The most recent function call tuple can in some cases be <code class="code">{Module,Name,[Arg],ExtraInfo}</code>.</p> </div> <div class="footer"> <hr> <p>Copyright © 2003-2022 Ericsson AB. All Rights Reserved.</p> </div><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2010&ndash;2022 Ericsson AB<br>Licensed under the Apache License, Version 2.0.<br>
    
  </p>
</div>
